#include "mainwindow.h"
#include "ui_mainwindow.h"

//App Specific QT Includes
#include "qfiledialog.h"
#include <QDateTime>
#include <QTimer>
#include <QTextStream>
#include <QCloseEvent>

//WiringPi Includes
#include <wiringPi.h>
#include <wiringPiI2C.h>
#include <wiringPiSPI.h>


#include "IO.h"

// Displays Specific Includes
extern "C" {

#include "M00794.h"
#include "VCNL4035.h"
#include "photo.h"
#include "program.h"

}



//Private
QFileInfo fileInfo;
QImage imageIn;

// Vishay Sensor i2c Addresses
int i2cH_VCNL;



QVector<char> ImageInArray;

//Public
QString JoyStick_Status;


MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    QTimer *timedService = new QTimer(this);
    connect(timedService, SIGNAL(timeout()), this, SLOT(update()) );

    // Initialize the Ice Cream HAT
    if (initIceCreamHat())
    {
        // Turn on interrupt timer
        timedService->start(50);


    }

}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::on_ApplicationExit()
{

    shutdown_Display();
}

void MainWindow::update()
{

    VCNL_readSensor();

    ui->label_Prox1->setText(QString::number(triggerVal_Prox[0]));
    ui->label_Prox2->setText(QString::number(triggerVal_Prox[1]));
    ui->label_Prox3->setText(QString::number(triggerVal_Prox[2]));

    ui->label_ALS ->setText(QString::number(valALS));
    ui->label_WHITE->setText(QString::number(valWHITE));

    int NewGesture = VCNL_GetGesture();

    if (NewGesture != GESTURE_NONE)
    {
        ui->label_JoyStick->setText(QString::number(NewGesture));
    }



    //all_R();
    //row_135();
    //img1();



}

void MainWindow::on_pushButton_LoadImage_clicked()
{

   QString filename = QFileDialog::getOpenFileName(this,
                     tr("Load an Image file"), "/home", tr("Image Files (*.png *.jpg *.jpeg *.bmp)"));
   if (loadImage(filename))
   {   
       ui->pushButton_SaveAsCCode->setEnabled(true);

       /*for (int i = 0; i < ui->listWidget_History->count(); i++)
       {
           if( !QString::compare( ui->listWidget_History->itemAt(i,0)->whatsThis(), filename, Qt::CaseInsensitive))
           {
              return;
           }
       }*/

       QListWidgetItem *item = new QListWidgetItem();
       item->setText(filename.section('/',-1));
       item->setWhatsThis(filename);

       //ui->listWidget_History->addItem(item);
   }
   else
   {
       ui->pushButton_SaveAsCCode->setDisabled(true);
   }

}


// Support Methods

// File load functions
int MainWindow::loadImage(QString filename)
{

    QFile file(filename);
    if (!file.open(QIODevice::ReadOnly))
           return 0;

    imageIn.load(filename);

    file.close();

    QFileInfo NewfileInfo(filename);

    if (imageIn.height() > 256 || imageIn.width() > 256 )
    {
        ui->label_Filename->setText("File Error: " + NewfileInfo.fileName() + " - Image size is too big. Please check your file and try again.");
        return 0;
    }

    fileInfo = NewfileInfo;

    ui->label_Filename->setText(fileInfo.fileName());


    imageIn = imageIn.convertToFormat(QImage::Format_Mono);

    int width = imageIn.width(), height = imageIn.height();

    //Setup output for C Header file

    QDateTime dt = QDateTime::currentDateTime();

    ui->textBrowser_CHeaderOutput->clear();

    ui->textBrowser_CHeaderOutput->append("//");
    ui->textBrowser_CHeaderOutput->append("// Header file for " + fileInfo.fileName() + "." );
    ui->textBrowser_CHeaderOutput->append("//");
    ui->textBrowser_CHeaderOutput->append("// Image Size: " + QString::number(width) + " x " + QString::number(height));
    ui->textBrowser_CHeaderOutput->append("//");
    ui->textBrowser_CHeaderOutput->append("// Generated by Visionox | VxD on " + dt.toString( "ddd, d MMM yyyy hh:mm:ss" ));
    ui->textBrowser_CHeaderOutput->append("//");

    ui->textBrowser_CHeaderOutput->append("");
    ui->textBrowser_CHeaderOutput->append("");
    ui->textBrowser_CHeaderOutput->append("const char array_image_" + ((fileInfo.fileName()).section('.', 0,0)).replace(" ","_") + "[] = " );
    ui->textBrowser_CHeaderOutput->append("{" );


    QColor color;
    unsigned char byteData = 0;
    QString ColPixels = "";

    ImageInArray.clear();

    for (int bank=0; bank<height/8; bank++)
    {
        ColPixels = "";

        for (int x=0; x<width; x++)
        {
            byteData = 0;

            for (int y=(0 + (bank*8)); y<(8+(bank*8)); y++)
            {
                color = imageIn.pixel(x, y);

                //int r = color.red();
                //int g = color.green();
                //int b = color.blue();

                byteData>>=1;

                if (color.red() > 127 || color.green() > 127 || color.blue() > 127 )
                //if ((color.red() + color.green() + color.blue())/3 > 127 )
                {
                    imageIn.setPixel(x, y, 1);
                    byteData = byteData | 0x80;
                }
                else
                {
                    imageIn.setPixel(x, y, 0);
                    byteData = byteData & 0x7F;
                }

            }

            //Store Image Data in Memory
            ImageInArray.append(byteData);

            //Write Image Data to Screen to save to file later
            QByteArray array((char * )&byteData, 1);

            ColPixels = ColPixels + " 0x" + QString(array.toHex()) + ",";
        }

        ui->textBrowser_CHeaderOutput->append(ColPixels);
    }

    ui->textBrowser_CHeaderOutput->append("" );
    ui->textBrowser_CHeaderOutput->append("};" );


    QGraphicsScene *scene = new QGraphicsScene (this);
    imageIn.invertPixels(QImage::InvertRgba);
    QPixmap pixmap = QPixmap::fromImage(imageIn);
    scene->addPixmap(pixmap);

    //int gVWidth = ((int)(256 / imageIn.width())) * imageIn.width();
    int gVHeight = ((int)(256 * imageIn.height())) / imageIn.width();

    ui->graphicsView_OLEDImage->resize(256, gVHeight);
    ui->graphicsView_OLEDImage->setScene(scene);
    ui->graphicsView_OLEDImage->fitInView(scene->sceneRect(),Qt::KeepAspectRatio);

    Image_Show();

    return 1;

}


void MainWindow::on_pushButton_SaveAsCCode_clicked()
{
    QString filename = QFileDialog::getSaveFileName(this,"Save " + fileInfo.fileName() + " as C file", fileInfo.path() + "/" + (fileInfo.fileName().section('.', 0,0)).replace(" ","_") + ".c"  ,"C File (*.c)");

    QFile file(filename);

    if ( file.open(QIODevice::ReadWrite) )
    {
        QTextStream stream( &file );
        stream << ui->textBrowser_CHeaderOutput->toPlainText();
    }
    file.flush();
    file.close();
}


//Initialize Ice Cream
int MainWindow::initIceCreamHat()
{
    uint8_t temp_buf[2];
    // Setup wiringPi to enable i/o and other port related functions

    wiringPiSetup();


    // Check if the Vishay VCNL4035 is present @ 0x60

    ui->label_Status->setText("Trying to connect...");
    QString msgRec = "";

    if(VCNL_init()<0 )
    {
        /* ERROR HANDLING: you can check errno to see what went wrong */
        perror("Failed to open the i2c bus");

        ui->label_Status->setText("BlueMoon not found (X)");

        return -1;
    }
    else
    {
        ui->label_Status->setText("VCNL configuration complete");
    }

    // ******************* Setup I/O ***********************

    ui->label_Status->setText("Setting I/O");

    // Setup pointers to funtions that will need to be passed through as paramters to other functions
    typedef void (*FunctionType)(void); //< We call the pointer to function type FunctionType (the line is optional and for simplicity).
    FunctionType pointerToVCNL_INT = &MainWindow::VCNL_INT; //< Literally means get the address of MyClass::someFunction and save it in the pointerToFunction variable.

    pinMode (4, INPUT) ; // VCNL INT
    pullUpDnControl(4, PUD_UP); // Pull-UP
    wiringPiISR(4, INT_EDGE_FALLING, pointerToVCNL_INT);

    //***************** Setup Display *****************

    setup_DisplayIO();

    init_LD7134();

    //all_R();
    //all_G();
    //all_B();
    //img1();
    //frame();
    //column2();


    ui->label_Status->setText("OLED and Prox drivers loaded");

    //ui->label_Status->setText("Rocky Road ready!");

    return 1;

}


// Load Image to Dislays
void MainWindow::Image_Show()
{
/*   uchar page_number,column_number;
   uint pixel=MIN;
   for(page_number=MIN;page_number<PAGE_TOTAL/2;page_number++)
   {
      Write_Command(START_PAGE+page_number);
      Write_Command(START_HIGH_BIT);
      Write_Command(START_LOW_BIT);
      for(column_number=MIN;column_number<COLUMN_MAX;column_number++)
      {
         Write_Data(ImageInArray.at(pixel));
         pixel++;
      }
  }
*/
}


void MainWindow::VCNL_INT()
{


}

// Joystick functions
void MainWindow::JoyUP_INT()
{

    JoyStick_Status = "UP";
    //Chess_Board1();

}

void MainWindow::JoyDOWN_INT()
{

    JoyStick_Status = "DOWN";

    //All_Screen();
}

void MainWindow::JoyLEFT_INT()
{

    JoyStick_Status = "LEFT";

    //V_pinture();
}

void MainWindow::JoyRIGHT_INT()
{

    JoyStick_Status = "RIGHT";

    //Clear_Screen();
}

void MainWindow::JoySELECT_INT()
{

    JoyStick_Status = "SELECT";

    //Image_Show();

}




void MainWindow::on_pushButton_4_clicked()
{
    frame();
}

void MainWindow::on_pushButton_clicked()
{
    all_R();
}

void MainWindow::on_pushButton_2_clicked()
{
    all_G();
}

void MainWindow::on_pushButton_3_clicked()
{
    all_B();
}

void MainWindow::on_Ipeak_sliderMoved(int position)
{
    ui->Peak_Current->setText(QString::number(position*16)+"uA");

    write_com(0x0f);	//Set Dot Matrix Peak Current Level (0-1008uA)
    write_dat((char)position);	//PR[5:0]	16uA Step
    write_dat((char)position);	//PG[5:0]	16uA Step
    write_dat((char)position);	//PB[5:0]	16uA Step
}
